# we want disable the MSBuild
build: off

deploy:
  release: WinesImages-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: xL9EhxFvxhagFiB2BM2WSpRgZZprk1Vci+GWkxtJkkAaWkR3F0lWXtnQeebMUwRv # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

build_script:
  - nuget pack Package.nuspec
